config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'home#index'

  resources :users do
    member do
      get :boards
      get :articles
      get :replies
    end
  end

  resources :boards do
    resources :posts, shallow: true
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
# frozen_string_literal: true

class Board < ApplicationRecord
  belongs_to :user
  has_many :posts, dependent: :destroy

  validates :name, presence: true
  validates :name, uniqueness: true
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  belongs_to :user
  belongs_to :board
  belongs_to :article, class_name: 'Post', optional: true
  has_many   :replies, class_name: 'Post', foreign_key: 'article_id', dependent: :destroy

  validates :content, presence: true

  scope :filter_articles, -> { where(article_id: nil) }
  scope :filter_replies, -> { where.not(article_id: nil) }
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_many :boards, dependent: :destroy
  has_many :posts, dependent: :destroy

  validates :username, :email, presence: true
  validates :username, :email, uniqueness: true
  validates :username, length: { minimum: 8 }
  validates :email, format: { with: /\A[\w.]+@example.com\Z/i,
                              message: 'must contain `@example.com` characters' }
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/boards_controller.rb
# frozen_string_literal: true

# Controll board action
class BoardsController < ApplicationController
  before_action :user, only: %i[create]
  before_action :find_board, only: %i[edit update destroy]

  def index
    @boards = Board.all.order(:created_at)
  end

  def new
    @board = Board.new
  end

  def create
    form = CreateBoardForm.new(owner: @user, name: board_params[:name])

    if form.save
      redirect_to boards_path, notice: 'Board successfully created'
    else
      flash[:errors] = form.errors.full_messages
      redirect_to new_board_path
    end
  end

  def edit; end

  def update
    if @board.update(board_params)
      redirect_to boards_path, notice: 'Board successfully updated'
    else
      flash[:errors] = @board.errors.full_messages
      redirect_to edit_board_path
    end
  end

  def destroy
    @board.destroy if @board.present?
    redirect_to boards_path, notice: 'Board successfully deleted'
  end

  private

  def find_board
    @board = Board.find_by(id: params[:id])
  end

  def user
    @user = User.find_by(username: params[:board][:username])
  end

  def board_params
    params.require(:board).permit(:name)
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

# Controll landing page action
class HomeController < ApplicationController
  def index; end
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

# Controll posts action
class PostsController < ApplicationController
  before_action :find_board
  before_action :find_user, only: %i[create]
  before_action :find_post, only: %i[edit update destroy]

  def index
    @posts = @board.posts.filter_articles
  end

  def new
    @post = @board.posts.new(article_id: params[:article_id])
  end

  def create
    form = CreatePostForm.new(board: @board, author: @user, params: post_params)

    if form.save
      redirect_to board_posts_path(@board), notice: 'Post successfully created'
    elsif form.article_id.present?
      flash[:errors] = form.errors.full_messages
      redirect_to board_posts_path(@board)
    else
      flash[:errors] = form.errors.full_messages
      redirect_to new_board_post_path
    end
  end

  def edit; end

  def update
    if @post.update(post_params)
      redirect_to board_posts_path(@post.board), notice: 'Post successfully updated'
    else
      flash[:errors] = @user.errors.full_messages
      redirect_to edit_post_path
    end
  end

  def destroy
    @post.destroy if @post.present?
    redirect_to board_posts_path(@post.board), notice: 'Post successfully deleted'
  end

  private

  def find_post
    @post = Post.find_by(id: params[:id])
  end

  def find_user
    @user = User.find_by(username: params[:post][:author])
  end

  def find_board
    @board = Board.find_by(id: params[:board_id])
  end

  def post_params
    params.require(:post).permit(:author, :content, :article_id)
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

# Controll users action
class UsersController < ApplicationController
  before_action :find_user, except: %i[index new create]

  def index
    @users = User.all.order(:created_at)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to users_path, notice: 'User successfully created'
    else
      flash[:errors] = @user.errors.full_messages
      redirect_to new_user_path
    end
  end

  def edit; end

  def update
    if @user.update(user_params)
      redirect_to users_path, notice: 'User successfully updated'
    else
      flash[:errors] = @user.errors.full_messages
      redirect_to edit_user_path
    end
  end

  def destroy
    @user.destroy if @user.present?
    redirect_to users_path, notice: 'User successfully deleted'
  end

  def boards
    @boards = @user.boards
  end

  def articles
    @posts = @user.posts.filter_articles
  end

  def replies
    @posts = @user.posts.filter_replies
  end

  private

  def find_user
    @user = User.find_by(id: params[:id])
  end

  def user_params
    params.require(:user).permit(:username, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/boards/edit.html.erb
<h4 class="title">Edit <%= @board.name %></h4>

<%= render 'shared/errors' %>

<div style="width: 25%; margin: auto;">
  <%= form_with model: @board, url: board_path do |form| %>

    <div class="mb-3">
      <%= form.label :name, class: 'form-label' %>
      <%= form.text_field :name, class: 'form-control' %>
    </div>

    <%= form.submit 'Update', class: 'btn btn-primary' %>
    <%= link_to 'Back', boards_path, type: 'button', class: 'btn btn-secondary' %>

  <% end %>
<div>

app/views/boards/index.html.erb
<h4 class="title">Board List</h4>

<%= link_to 'Create Board', new_board_path, type: 'button', class: 'btn btn-primary create-btn' %>

<table class="table table-hover">
  <thead class="table-light">
    <tr>
      <th scope="col">Board Name</th>
      <th scope="col">Owner (username)</th>
      <th scope="col">Manage Board</th>
      <th scope="col">Manage Article</th>
    </tr>
  </thead>
  <tbody>
    <% @boards.each do |board| %>
    <tr>
      <td><%= board.name %></td>
      <td><%= board.user.username %></td>
      <td>
        <%= link_to 'Edit', edit_board_path(board), type: 'button', class: 'btn btn-primary create-btn' %>
        <%= link_to 'Delete', board_path(board),
              data: {confirm: "Are you sure to delete #{board.name}?"}, method: :delete,
              type: 'button', class: 'btn btn-secondary create-btn' %>
      </td>
      <td>
        <%= link_to 'Add Article', new_board_post_path(board), type: 'button', class: 'btn btn-primary create-btn' %>
        <%= link_to 'All Articles', board_posts_path(board), type: 'button', class: 'btn btn-primary create-btn' %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/boards/new.html.erb
<h4 class="title">Create New Board</h4>

<%= render 'shared/errors' %>

<div style="width: 25%; margin: auto;">
  <%= form_with model: @board, url: boards_path do |form| %>

    <div class="mb-3">
      <%= form.label :username, 'Owner (username)', class: 'form-label' %>
      <%= form.text_field :username, class: 'form-control' %>
      <div class="form-text">NOTICE: owner cannot be modified after board created.</div>
    </div>

    <div class="mb-3">
      <%= form.label :name, class: 'form-label' %>
      <%= form.text_field :name, class: 'form-control' %>
    </div>

    <%= form.submit 'Create Board', class: 'btn btn-primary' %>
    <%= link_to 'Back', boards_path, type: 'button', class: 'btn btn-secondary' %>

  <% end %>
<div>

app/views/home/index.html.erb
<h4 class="title">Dashboard</h4>

<%= link_to 'User List', users_path, type: 'button', class: 'btn btn-primary' %>
<%= link_to 'Board List', boards_path, type: 'button', class: 'btn btn-primary' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogPostingSystem</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #e3f2fd;">
      <div class="container-fluid">
        <%= link_to 'Blog Posting System', root_path, class: 'navbar-brand' %>
        <div class="collapse navbar-collapse" id="navbarText">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <%= link_to 'Dashboard', root_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to 'User List', users_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to 'Board List', boards_path, class: 'nav-link' %>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <div style="padding: 1rem;">
      <p style="color: green"><%= notice %></p>
      <%= yield %>
    </div>
  </body>
</html>

app/views/posts/_reply.html.erb
<div class="card">
  <div class="card-body">
    <div style="color: gray;">
      @<%= User.find(reply.user.id).username %>
    </div>
    <%= reply.content %>
    <div class="d-grid gap-2 d-md-flex justify-content-md-end">
      <%= link_to 'Edit', edit_post_path(reply) %>
      <%= link_to 'Delete', post_path(reply),
            data: {confirm: "Are you sure to delete this post?"}, method: :delete, style: 'color: grey;' %>
      <%= link_to 'Reply', new_board_post_path(reply.board, article_id: reply.id), remote: true %>
    </div>
  </div>
</div>

<%# show replies of reply %>
<% if reply.replies.any? %>
  <% reply.replies.each do |reply| %>
    <div style="margin-left: 3rem;">
      <%= render partial: 'posts/reply', locals: { reply: reply } %>
    </div>
  <% end %>
<% end %>

<%# show reply form of reply %>
<div id="reply-form-<%= reply.id %>"></div>

app/views/posts/_reply_form.html.erb
<div class="card ml-5">
  <div class="card-body">
    <%= form_with(model: [@board, @post]) do |f| %>
      <%= f.hidden_field :article_id %>

      <div class="form-group">
        <div class="mb-3">
          <%= f.label :reply %>
        </div>

        <div class="mb-3">
          <%= f.label :author, 'Author (username)', class: 'form-label' %>
          <%= f.text_field :author, class: 'form-control' %>
          <div class="form-text">NOTICE: author cannot be modified after board created.</div>
        </div>

        <div class="mb-3">
          <%= f.label :content, class: 'form-label' %>
          <%= f.text_area :content, class: 'form-control' %>
        </div>
      </div>

      <%= f.submit 'Submit', class: 'btn btn-primary' %>
      <%= link_to 'Cancel', board_posts_path(@board), class: 'btn btn-secondary' %>
    <% end %>
  </div>
</div>

app/views/posts/edit.html.erb
<h4 class="title">Edit Post</h4>

<%= render 'shared/errors' %>

<div style="width: 25%; margin: auto;">
  <%= form_with model: @post, url: post_path do |form| %>

    <div class="mb-3">
      <%= form.label :board, 'Board: ', class: 'form-label' %>
      <%= @post.board.name %>
    </div>

    <div class="mb-3">
      <%= form.label :author, 'Author: ', class: 'form-label' %>
      <%= @post.user.username %>
    </div>

    <div class="mb-3">
      <%= form.label :content, class: 'form-label' %>
      <%= form.text_area :content, class: 'form-control textarea' %>
    </div>

    <%= form.submit 'Update', class: 'btn btn-primary' %>
    <%= link_to 'Back', board_posts_path(@post.board), type: 'button', class: 'btn btn-secondary' %>

  <% end %>
<div>

app/views/posts/index.html.erb
<h4 class="title"><%= @board.name.upcase %> - Post List</h4>

<%= render 'shared/errors' %>

<%= link_to 'Back', boards_path, type: 'button', class: 'btn btn-secondary create-btn' %>

<div class="row row-cols-1 row-cols-md-3 g-4">
  <% @posts.each do |post| %>
    <div class="col">
      <div class="card text-center">
        <div class="card-header">
          @<%= User.find(post.user_id).username %>
        </div>
        <div class="card-body">
          <p class="card-text"><%= truncate(post.content, length: 60) %></p>
          <%= link_to 'Edit', edit_post_path(post), type: 'button', class: 'btn btn-primary create-btn' %>
          <%= link_to 'Delete', post_path(post),
                data: {confirm: "Are you sure to delete this post?"}, method: :delete,
                type: 'button', class: 'btn btn-secondary create-btn' %>
          <%= link_to 'Reply', new_board_post_path(post.board, article_id: post.id), remote: true, type: 'button', class: 'btn btn-outline-primary' %>
        </div>
      </div>

      <%# show replies of article %>
      <% if post.replies.any? %>
        <% post.replies.each do |reply| %> 
          <%= render partial: 'posts/reply', locals: { reply: reply } %>
        <% end %>
      <% end %>

      <%# show reply form of article %>
      <div id="reply-form-<%= post.id %>"></div>
    </div>
  <% end %>
</div>

app/views/posts/new.html.erb
<h4 class="title">Create New Article</h4>

<%= render 'shared/errors' %>

<div style="width: 25%; margin: auto;">
  <%= form_with model: @post, url: board_posts_path do |form| %>

    <div class="mb-3">
      <%= form.label :board, 'Board: ', class: 'form-label' %>
      <%= @board.name %>
    </div>

    <div class="mb-3">
      <%= form.label :author, 'Author (username)', class: 'form-label' %>
      <%= form.text_field :author, class: 'form-control' %>
      <div class="form-text">NOTICE: author cannot be modified after board created.</div>
    </div>

    <div class="mb-3">
      <%= form.label :content, class: 'form-label' %>
      <%= form.text_area :content, class: 'form-control textarea' %>
    </div>

    <%= form.submit 'Create Post', class: 'btn btn-primary' %>
    <%= link_to 'Back', boards_path, type: 'button', class: 'btn btn-secondary' %>

  <% end %>
<div>

app/views/posts/new.js.erb
document.querySelector("#reply-form-<%= @post.article_id %>").innerHTML = ("<%= j render 'reply_form' %>")

app/views/shared/_errors.html.erb
<% if flash[:errors] %>
  <ul>
  <% flash[:errors].each do |error| %>
    <li class="error"><%= error %></li>
  <% end %>
  <ul>
<% end %>

app/views/users/_posts.html.erb
<%= link_to 'Back', users_path, type: 'button', class: 'btn btn-secondary create-btn' %>

<div class="row row-cols-1 row-cols-md-3 g-4">
  <% @posts.each do |post| %>
    <div class="col">
      <div class="card text-center">
        <div class="card-header">
          @<%= @user.username %>
        </div>
        <div class="card-body">
          <p class="card-text"><%= truncate(post.content, length: 60) %></p>
          <%= link_to 'Edit', edit_post_path(post), type: 'button', class: 'btn btn-primary create-btn' %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/users/articles.html.erb
<h4 class="title"><%= @user.username.upcase %> - Article List</h4>

<%= render 'posts' %>

app/views/users/boards.html.erb
<h4 class="title"><%= @user.username.upcase %> - Board List</h4>

<%= link_to 'Back', users_path, type: 'button', class: 'btn btn-secondary create-btn' %>

<table class="table table-hover">
  <thead class="table-light">
    <tr>
      <th scope="col">Board Name</th>
      <th scope="col">Owner (username)</th>
    </tr>
  </thead>
  <tbody>
    <% @boards.each do |board| %>
    <tr>
      <td><%= board.name %></td>
      <td><%= board.user.username %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/users/edit.html.erb
<h4 class="title">Edit <%= @user.username %> profile</h4>

<%= render 'shared/errors' %>

<div style="width: 25%; margin: auto;">
  <%= form_with model: @user, url: user_path do |form| %>

    <div class="mb-3">
      <%= form.label :email, class: 'form-label' %>
      <%= form.text_field :email, class: 'form-control' %>
    </div>

    <%= form.submit 'Update', class: 'btn btn-primary' %>
    <%= link_to 'Back', users_path, type: 'button', class: 'btn btn-secondary' %>

  <% end %>
<div>

app/views/users/index.html.erb
<h4 class="title">User List</h4>

<%= link_to 'Create User', new_user_path, type: 'button', class: 'btn btn-primary create-btn' %>

<table class="table table-hover">
  <thead class="table-light">
    <tr>
      <th scope="col">Username</th>
      <th scope="col">Email</th>
      <th scope="col">Manage User</th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
    <tr>
      <td><%= user.username %></td>
      <td><%= user.email %></td>
      <td>
        <%= link_to 'Edit', edit_user_path(user), type: 'button', class: 'btn btn-primary create-btn' %>
        <%= link_to 'Delete', user_path(user),
              data: {confirm: "Are you sure to delete #{user.username}?"}, method: :delete,
              type: 'button', class: 'btn btn-secondary create-btn' %>
      </td>
      <td>
        <%= link_to 'All Boards', boards_user_path(user), type: 'button', class: 'btn btn-primary create-btn' %>
        <%= link_to 'All Articles', articles_user_path(user), type: 'button', class: 'btn btn-primary create-btn' %>
        <%= link_to 'All Replies', replies_user_path(user), type: 'button', class: 'btn btn-primary create-btn' %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/users/new.html.erb
<h4 class="title">Create New User</h4>

<%= render 'shared/errors' %>

<div style="width: 25%; margin: auto;">
  <%= form_with model: @user, url: users_path do |form| %>

    <div class="mb-3">
      <%= form.label :username, class: 'form-label' %>
      <%= form.text_field :username, class: 'form-control' %>
      <div class="form-text">NOTICE: username cannot be modified after user created.</div>
    </div>

    <div class="mb-3">
      <%= form.label :email, class: 'form-label' %>
      <%= form.text_field :email, class: 'form-control' %>
    </div>

    <%= form.submit 'Create User', class: 'btn btn-primary' %>
    <%= link_to 'Back', users_path, type: 'button', class: 'btn btn-secondary' %>

  <% end %>
<div>

app/views/users/replies.html.erb
<h4 class="title"><%= @user.username.upcase %> - Reply List</h4>

<%= render 'posts' %>